drop table hook CASCADE ;
drop table arena cascade;
drop table users cascade;
drop table tributes cascade;
drop table district cascade;
drop table prices cascade;
drop table weaponsInGame  cascade;
drop table game cascade;
drop table statuses cascade;
drop table presentstotribute CASCADE;
drop table shop cascade;
drop table userSkills cascade;
drop table trainings cascade;
drop table productsAndLocation cascade;
drop table skills cascade;
drop table weapons cascade;
drop table userLogin CASCADE ;
drop table location CASCADE ;