drop table hook CASCADE ;
drop table arena cascade;
drop table users cascade;
drop table tribute cascade;
drop table district cascade;
drop table price cascade;
drop table weapons_in_game  cascade;
drop table game cascade;
drop table status cascade;
drop table presents_to_tribute CASCADE;
drop table shop cascade;
drop table user_skill cascade;
drop table training cascade;
drop table products_and_location cascade;
drop table skill cascade;
drop table weapon cascade;
drop table user_login CASCADE ;
drop table location CASCADE ;