drop table arenas cascade;
drop table users cascade;
drop table tributes cascade;
drop table districts cascade;
drop table prices cascade;
drop table weaponsInGame  cascade;
drop table games cascade;
drop table statuses cascade;
drop table presentstotributes CASCADE;
drop table shop cascade;
drop table userSkills cascade;
drop table trainings cascade;
drop table productsAndLocation cascade;
drop table skills cascade;
drop table weapons cascade;
drop table userlogin CASCADE ;
drop table locations CASCADE ;