INSERT INTO price values (1,"salary", 1000);
insert into status values (1, "viewer", 1);
INSERT INTO district VALUES (0,'Капитолий','Управление',0);
INSERT INTO district VALUES (1,'Дистрикт 1','Роскошь',1);
INSERT INTO district VALUES (2,'Дистрикт 2','Оружие',2);
INSERT INTO district VALUES (3,'Дистрикт 3','Электроника',3);
INSERT INTO district VALUES (4,'Дистрикт 4','Рыболовство',4);
INSERT INTO district VALUES (5,'Дистрикт 5','Энергетика',5);
INSERT INTO district VALUES (6,'Дистрикт 6','Транспорт',6);
INSERT INTO district VALUES (7,'Дистрикт 7','Древесина',7);
INSERT INTO district VALUES (8,'Дистрикт 8','Текстиль',8);
INSERT INTO district VALUES (9,'Дистрикт 9','Сельское хозяйство',9);
INSERT INTO district VALUES (10,'Дистрикт 10','Животноводство',10);
INSERT INTO district VALUES (11,'Дистрикт 11','Сельское хозяйство',11);
INSERT INTO district VALUES (12,'Дистрикт 12','Добыча угля',12);